name: fit_parser
description: "A .fit file format parsing library. fit stands for Flexible and
             Interoperable Data Transfer. It is a file format for tracking 
             sports activities with smart watches and the like."
version: 0.1.8
homepage: https://github.com/3schweinehunde/fit_parser

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
