name: fit_parser
description: A starting point for Dart libraries or applications.
version: 0.0.2
homepage: https://github.com/3schweinehunde/fit_parser

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
