import 'package:dart/src/values/activity_values.dart';
import 'package:dart/src/values/bike_light_beam_angle_mode_values.dart';
import 'package:dart/src/values/checksum_values.dart';
import 'package:dart/src/values/course_point_values.dart';
import 'package:dart/src/values/date_mode_values.dart';
import 'package:dart/src/values/display_heart_values.dart';
import 'package:dart/src/values/display_power_values.dart';
import 'package:dart/src/values/dive_alarm_type_values.dart';
import 'package:dart/src/values/dive_backlight_mode_values.dart';
import 'package:dart/src/values/dive_gas_status_values.dart';
import 'package:dart/src/values/activity_class_values.dart';
import 'package:dart/src/values/activity_level_values.dart';
import 'package:dart/src/values/activity_subtype_values.dart';
import 'package:dart/src/values/activity_type_values.dart';
import 'package:dart/src/values/analog_watchface_layout_values.dart';
import 'package:dart/src/values/ant_network_values.dart';
import 'package:dart/src/values/antplus_device_type_values.dart';
import 'package:dart/src/values/attitude_stage_values.dart';
import 'package:dart/src/values/attitude_validity_values.dart';
import 'package:dart/src/values/auto_activity_detect_values.dart';
import 'package:dart/src/values/auto_sync_frequency_values.dart';
import 'package:dart/src/values/autolap_trigger_values.dart';
import 'package:dart/src/values/autoscroll_values.dart';
import 'package:dart/src/values/backlight_mode_values.dart';
import 'package:dart/src/values/battery_status_values.dart';
import 'package:dart/src/values/bench_press_exercise_name_values.dart';
import 'package:dart/src/values/bike_light_network_config_type_values.dart';
import 'package:dart/src/values/body_location_values.dart';
import 'package:dart/src/values/bp_status_values.dart';
import 'package:dart/src/values/calf_raise_exercise_name_values.dart';
import 'package:dart/src/values/camera_event_type_values.dart';
import 'package:dart/src/values/camera_orientation_type_values.dart';
import 'package:dart/src/values/cardio_exercise_name_values.dart';
import 'package:dart/src/values/carry_exercise_name_values.dart';
import 'package:dart/src/values/chop_exercise_name_values.dart';
import 'package:dart/src/values/comm_timeout_type_values.dart';
import 'package:dart/src/values/connectivity_capabilities_values.dart';
import 'package:dart/src/values/core_exercise_name_values.dart';
import 'package:dart/src/values/course_capabilities_values.dart';
import 'package:dart/src/values/crunch_exercise_name_values.dart';
import 'package:dart/src/values/curl_exercise_name_values.dart';
import 'package:dart/src/values/day_of_week_values.dart';
import 'package:dart/src/values/deadlift_exercise_name_values.dart';
import 'package:dart/src/values/digital_watchface_layout_values.dart';
import 'package:dart/src/values/display_measure_values.dart';
import 'package:dart/src/values/display_orientation_values.dart';
import 'package:dart/src/values/display_position_values.dart';
import 'package:dart/src/values/event_type_values.dart';
import 'package:dart/src/values/event_values.dart';
import 'package:dart/src/values/exd_data_units_values.dart';
import 'package:dart/src/values/exd_descriptors_values.dart';
import 'package:dart/src/values/exd_display_type.dart';
import 'package:dart/src/values/exd_layout_values.dart';
import 'package:dart/src/values/exd_qualifiers_values.dart';
import 'package:dart/src/values/exercise_category_values.dart';
import 'package:dart/src/values/favero_product_values.dart';
import 'package:dart/src/values/file_flags_values.dart';
import 'package:dart/src/values/file_values.dart';
import 'package:dart/src/values/fit_base_type_values.dart';
import 'package:dart/src/values/fit_base_unit_values.dart';
import 'package:dart/src/values/fitness_equipment_state_values.dart';
import 'package:dart/src/values/flye_exercise_name_values.dart';
import 'package:dart/src/values/garmin_product_values.dart';
import 'package:dart/src/values/gender_values.dart';
import 'package:dart/src/values/goal_recurrence_values.dart';
import 'package:dart/src/values/goal_source_values.dart';
import 'package:dart/src/values/goal_values.dart';
import 'package:dart/src/values/hip_raise_exercise_name_values.dart';
import 'package:dart/src/values/hip_stability_exercise_name_values.dart';
import 'package:dart/src/values/hip_swing_exercise_name_values.dart';
import 'package:dart/src/values/hr_type_values.dart';
import 'package:dart/src/values/hr_zone_calc_values.dart';
import 'package:dart/src/values/hyperextension_exercise_name_values.dart';
import 'package:dart/src/values/intensity_values.dart';
import 'package:dart/src/values/language_bits_0_values.dart';
import 'package:dart/src/values/language_bits_1_values.dart';
import 'package:dart/src/values/language_bits_2_values.dart';
import 'package:dart/src/values/language_bits_3_values.dart';
import 'package:dart/src/values/language_bits_4_values.dart';
import 'package:dart/src/values/language_values.dart';
import 'package:dart/src/values/lap_trigger_values.dart';
import 'package:dart/src/values/lateral_raise_exercise_name_values.dart';
import 'package:dart/src/values/left_right_balance_100_values.dart';
import 'package:dart/src/values/left_right_balance_values.dart';
import 'package:dart/src/values/leg_curl_exercise_name_values.dart';
import 'package:dart/src/values/leg_raise_exercise_name_values.dart';
import 'package:dart/src/values/length_type_values.dart';
import 'package:dart/src/values/lunge_exercise_name_values.dart';
import 'package:dart/src/values/manufacturer_values.dart';
import 'package:dart/src/values/mesg_count_values.dart';
import 'package:dart/src/values/mesg_num_values.dart';
import 'package:dart/src/values/message_index_values.dart';
import 'package:dart/src/values/olympic_lift_exercise_name_values.dart';
import 'package:dart/src/values/plank_exercise_name_values.dart';
import 'package:dart/src/values/plyo_exercise_name_values.dart';
import 'package:dart/src/values/power_phase_type_values.dart';
import 'package:dart/src/values/pull_up_exercise_name_values.dart';
import 'package:dart/src/values/push_up_exercise_name_values.dart';
import 'package:dart/src/values/pwr_zone_calc_values.dart';
import 'package:dart/src/values/rider_position_type_values.dart';
import 'package:dart/src/values/row_exercise_name_values.dart';
import 'package:dart/src/values/run_exercise_name_values.dart';
import 'package:dart/src/values/schedule_values.dart';
import 'package:dart/src/values/segment_delete_status_values.dart';
import 'package:dart/src/values/segment_lap_status_values.dart';
import 'package:dart/src/values/segment_leaderboard_type_values.dart';
import 'package:dart/src/values/segment_selection_type_values.dart';
import 'package:dart/src/values/sensor_type_values.dart';
import 'package:dart/src/values/session_trigger_values.dart';
import 'package:dart/src/values/set_type_values.dart';
import 'package:dart/src/values/shoulder_press_exercise_name_values.dart';
import 'package:dart/src/values/shoulder_stability_exercise_name_values.dart';
import 'package:dart/src/values/shrug_exercise_name_values.dart';
import 'package:dart/src/values/side_values.dart';
import 'package:dart/src/values/sit_up_exercise_name_values.dart';
import 'package:dart/src/values/source_type_values.dart';
import 'package:dart/src/values/sport_bits_0_values.dart';
import 'package:dart/src/values/sport_bits_1_values.dart';
import 'package:dart/src/values/sport_bits_2_values.dart';
import 'package:dart/src/values/sport_bits_3_values.dart';
import 'package:dart/src/values/sport_bits_4_values.dart';
import 'package:dart/src/values/sport_bits_5_values.dart';
import 'package:dart/src/values/sport_event_values.dart';
import 'package:dart/src/values/sport_values.dart';
import 'package:dart/src/values/squat_exercise_name_values.dart';
import 'package:dart/src/values/stroke_type_values.dart';
import 'package:dart/src/values/sub_sport_values.dart';
import 'package:dart/src/values/supported_exd_screen_layouts_values.dart';
import 'package:dart/src/values/swim_stroke_values.dart';
import 'package:dart/src/values/switch_values.dart';
import 'package:dart/src/values/time_mode_values.dart';
import 'package:dart/src/values/time_zone_values.dart';
import 'package:dart/src/values/timer_trigger_values.dart';
import 'package:dart/src/values/tone_values.dart';
import 'package:dart/src/values/total_body_exercise_name_values.dart';
import 'package:dart/src/values/triceps_extension_exercise_name_values.dart';
import 'package:dart/src/values/turn_type_values.dart';
import 'package:dart/src/values/user_local_id_values.dart';
import 'package:dart/src/values/warm_up_exercise_name_values.dart';
import 'package:dart/src/values/watchface_mode_values.dart';
import 'package:dart/src/values/water_type_values.dart';
import 'package:dart/src/values/weather_report_values.dart';
import 'package:dart/src/values/weather_severe_type_values.dart';
import 'package:dart/src/values/weather_severity_values.dart';
import 'package:dart/src/values/weather_status_values.dart';
import 'package:dart/src/values/wkt_step_duration_values.dart';
import 'package:dart/src/values/wkt_step_target_values.dart';
import 'package:dart/src/values/workout_capabilities_values.dart';
import 'package:dart/src/values/workout_equipment_values.dart';

class FitType {
  Map type = {
// A
    'activity': activity_values,
    'activity_class': activity_class_values,
    'activity_level': activity_level_values,
    'activity_subtype': activity_subtype_values,
    'activity_type': activity_type_values,
    'analog_watchface_layout': analog_watchface_layout_values,
    'ant_network': ant_network_values,
    'antplus_device_type': antplus_device_type_values,
    'attitude_stage': attitude_stage_values,
    'attitude_validity': attitude_validity_values,
    'auto_activity_detect': auto_activity_detect_values,
    'autolap_trigger': autolap_trigger_values,
    'autoscroll': autoscroll_values,
    'auto_sync_frequency': auto_sync_frequency_values,
// B
    'backlight_mode': backlight_mode_values,
    'backlight_timeout': {0: 'infinite', },
    'battery_status': battery_status_values,
    'bench_press_exercise_name': bench_press_exercise_name_values,
    'bike_light_beam_angle_mode': bike_light_beam_angle_mode_values,
    'bike_light_network_config_type': bike_light_network_config_type_values,
    'body_location': body_location_values,
    'bp_status': bp_status_values,
// C
    'calf_raise_exercise_name': calf_raise_exercise_name_values,
    'camera_event_type': camera_event_type_values,
    'camera_orientation_type': camera_orientation_type_values,
    'cardio_exercise_name': cardio_exercise_name_values,
    'carry_exercise_name': carry_exercise_name_values,
    'checksum': checksum_values,
    'chop_exercise_name': chop_exercise_name_values,
    'comm_timeout_type': comm_timeout_type_values,
    'connectivity_capabilities': connectivity_capabilities_values,
    'core_exercise_name': core_exercise_name_values,
    'course_capabilities': course_capabilities_values,
    'course_point': course_point_values,
    'crunch_exercise_name': crunch_exercise_name_values,
    'curl_exercise_name': curl_exercise_name_values,
// D
    'date_mode': date_mode_values,
    'date_time': {0x10000000: 'min', },
    'day_of_week': day_of_week_values,
    'deadlift_exercise_name': deadlift_exercise_name_values,
    'device_index': {0: 'creator', },
    'digital_watchface_layout': digital_watchface_layout_values,
    'display_heart': display_heart_values,
    'display_measure': display_measure_values,
    'display_orientation': display_orientation_values,
    'display_position': display_position_values,
    'display_power': display_power_values,
    'dive_alarm_type': dive_alarm_type_values,
    'dive_backlight_mode': dive_backlight_mode_values,
    'dive_gas_status': dive_gas_status_values,
// E
    'event': event_values,
    'event_type': event_type_values,
    'exd_data_units': exd_data_units_values,
    'exd_descriptors': exd_descriptors_values,
    'exd_display_type': exd_display_type_values,
    'exd_layout': exd_layout_values,
    'exd_qualifiers': exd_qualifiers_values,
    'exercise_category': exercise_category_values,
// F
    'favero_product': favero_product_values,
    'file': file_values,
    'file_flags': file_flags_values,
    'fit_base_type': fit_base_type_values,
    'fit_base_unit': fit_base_unit_values,
    'fitness_equipment_state': fitness_equipment_state_values,
    'flye_exercise_name': flye_exercise_name_values,
// G
    'garmin_product': garmin_product_values,
    'gender': gender_values,
    'goal': goal_values,
    'goal_recurrence': goal_recurrence_values,
    'goal_source': goal_source_values,
// H
    'hip_raise_exercise_name': hip_raise_exercise_name_values,
    'hip_stability_exercise_name': hip_stability_exercise_name_values,
    'hip_swing_exercise_name': hip_swing_exercise_name_values,
    'hr_type': hr_type_values,
    'hr_zone_calc': hr_zone_calc_values,
    'hyperextension_exercise_name': hyperextension_exercise_name_values,
// I
    'intensity': intensity_values,
// L
    'language': language_values,
    'language_bits_0': language_bits_0_values,
    'language_bits_1': language_bits_1_values,
    'language_bits_2': language_bits_2_values,
    'language_bits_3': language_bits_3_values,
    'language_bits_4': language_bits_4_values,
    'lap_trigger': lap_trigger_values,
    'lateral_raise_exercise_name': lateral_raise_exercise_name_values,
    'left_right_balance': left_right_balance_values,
    'left_right_balance_100': left_right_balance_100_values,
    'leg_curl_exercise_name': leg_curl_exercise_name_values,
    'leg_raise_exercise_name': leg_raise_exercise_name_values,
    'length_type': length_type_values,
    'local_date_time': {0x10000000: 'min', },
    'lunge_exercise_name': lunge_exercise_name_values,
// M
    'manufacturer': manufacturer_values,
    'mesg_count': mesg_count_values,
    'mesg_num': mesg_num_values,
    'message_index': message_index_values,
// O
    'olympic_lift_exercise_name': olympic_lift_exercise_name_values,
// P
    'plank_exercise_name': plank_exercise_name_values,
    'plyo_exercise_name': plyo_exercise_name_values,
    'power_phase_type': power_phase_type_values,
    'pull_up_exercise_name': pull_up_exercise_name_values,
    'push_up_exercise_name': push_up_exercise_name_values,
    'pwr_zone_calc': pwr_zone_calc_values,
// R
    'rider_position_type': rider_position_type_values,
    'row_exercise_name': row_exercise_name_values,
    'run_exercise_name': run_exercise_name_values,
// S
    'schedule': schedule_values,
    'segment_delete_status': segment_delete_status_values,
    'segment_lap_status': segment_lap_status_values,
    'segment_leaderboard_type': segment_leaderboard_type_values,
    'segment_selection_type': segment_selection_type_values,
    'sensor_type': sensor_type_values,
    'session_trigger': session_trigger_values,
    'set_type': set_type_values,
    'shoulder_press_exercise_name': shoulder_press_exercise_name_values,
    'shoulder_stability_exercise_name': shoulder_stability_exercise_name_values,
    'shrug_exercise_name': shrug_exercise_name_values,
    'side': side_values,
    'sit_up_exercise_name': sit_up_exercise_name_values,
    'source_type': source_type_values,
    'sport': sport_values,
    'sport_bits_0': sport_bits_0_values,
    'sport_bits_1': sport_bits_1_values,
    'sport_bits_2': sport_bits_2_values,
    'sport_bits_3': sport_bits_3_values,
    'sport_bits_4': sport_bits_4_values,
    'sport_bits_5': sport_bits_5_values,
    'sport_bits_6': {0x01: 'floor_climbing', },
    'sport_event': sport_event_values,
    'squat_exercise_name': squat_exercise_name_values,
    'stroke_type': stroke_type_values,
    'sub_sport': sub_sport_values,
    'supported_exd_screen_layouts': supported_exd_screen_layouts_values,
    'swim_stroke': swim_stroke_values,
    'switch': switch_values,
// T
    'time_mode': time_mode_values,
    'time_zone': time_zone_values,
    'timer_trigger': timer_trigger_values,
    'tissue_model_type': {0: 'zhl_16c', },
    'tone': tone_values,
    'total_body_exercise_name': total_body_exercise_name_values,
    'triceps_extension_exercise_name': triceps_extension_exercise_name_values,
    'turn_type': turn_type_values,
// U
    'user_local_id': user_local_id_values,
// W
    'warm_up_exercise_name': warm_up_exercise_name_values,
    'watchface_mode': watchface_mode_values,
    'water_type': water_type_values,
    'weather_report': weather_report_values,
    'weather_severe_type': weather_severe_type_values,
    'weather_severity': weather_severity_values,
    'weather_status': weather_status_values,
    'weight': {0xFFFE: 'calculating', },
    'wkt_step_duration': wkt_step_duration_values,
    'wkt_step_target': wkt_step_target_values,
    'workout_capabilities': workout_capabilities_values,
    'workout_equipment': workout_equipment_values,
    'workout_hr': {100: 'bpm_offset', },
    'workout_power': {1000: 'watts_offset', },
  };
}