import 'package:fit_parser/src/values/activity_values.dart';
import 'package:fit_parser/src/values/bike_light_beam_angle_mode_values.dart';
import 'package:fit_parser/src/values/checksum_values.dart';
import 'package:fit_parser/src/values/course_point_values.dart';
import 'package:fit_parser/src/values/date_mode_values.dart';
import 'package:fit_parser/src/values/display_heart_values.dart';
import 'package:fit_parser/src/values/display_power_values.dart';
import 'package:fit_parser/src/values/dive_alarm_type_values.dart';
import 'package:fit_parser/src/values/dive_backlight_mode_values.dart';
import 'package:fit_parser/src/values/dive_gas_status_values.dart';
import 'package:fit_parser/src/values/activity_class_values.dart';
import 'package:fit_parser/src/values/activity_level_values.dart';
import 'package:fit_parser/src/values/activity_subtype_values.dart';
import 'package:fit_parser/src/values/activity_type_values.dart';
import 'package:fit_parser/src/values/analog_watchface_layout_values.dart';
import 'package:fit_parser/src/values/ant_network_values.dart';
import 'package:fit_parser/src/values/antplus_device_type_values.dart';
import 'package:fit_parser/src/values/attitude_stage_values.dart';
import 'package:fit_parser/src/values/attitude_validity_values.dart';
import 'package:fit_parser/src/values/auto_activity_detect_values.dart';
import 'package:fit_parser/src/values/auto_sync_frequency_values.dart';
import 'package:fit_parser/src/values/autolap_trigger_values.dart';
import 'package:fit_parser/src/values/autoscroll_values.dart';
import 'package:fit_parser/src/values/backlight_mode_values.dart';
import 'package:fit_parser/src/values/battery_status_values.dart';
import 'package:fit_parser/src/values/bench_press_exercise_name_values.dart';
import 'package:fit_parser/src/values/bike_light_network_config_type_values.dart';
import 'package:fit_parser/src/values/body_location_values.dart';
import 'package:fit_parser/src/values/bp_status_values.dart';
import 'package:fit_parser/src/values/calf_raise_exercise_name_values.dart';
import 'package:fit_parser/src/values/camera_event_type_values.dart';
import 'package:fit_parser/src/values/camera_orientation_type_values.dart';
import 'package:fit_parser/src/values/cardio_exercise_name_values.dart';
import 'package:fit_parser/src/values/carry_exercise_name_values.dart';
import 'package:fit_parser/src/values/chop_exercise_name_values.dart';
import 'package:fit_parser/src/values/comm_timeout_type_values.dart';
import 'package:fit_parser/src/values/connectivity_capabilities_values.dart';
import 'package:fit_parser/src/values/core_exercise_name_values.dart';
import 'package:fit_parser/src/values/course_capabilities_values.dart';
import 'package:fit_parser/src/values/crunch_exercise_name_values.dart';
import 'package:fit_parser/src/values/curl_exercise_name_values.dart';
import 'package:fit_parser/src/values/day_of_week_values.dart';
import 'package:fit_parser/src/values/deadlift_exercise_name_values.dart';
import 'package:fit_parser/src/values/digital_watchface_layout_values.dart';
import 'package:fit_parser/src/values/display_measure_values.dart';
import 'package:fit_parser/src/values/display_orientation_values.dart';
import 'package:fit_parser/src/values/display_position_values.dart';
import 'package:fit_parser/src/values/event_type_values.dart';
import 'package:fit_parser/src/values/event_values.dart';
import 'package:fit_parser/src/values/exd_data_units_values.dart';
import 'package:fit_parser/src/values/exd_descriptors_values.dart';
import 'package:fit_parser/src/values/exd_display_type.dart';
import 'package:fit_parser/src/values/exd_layout_values.dart';
import 'package:fit_parser/src/values/exd_qualifiers_values.dart';
import 'package:fit_parser/src/values/exercise_category_values.dart';
import 'package:fit_parser/src/values/favero_product_values.dart';
import 'package:fit_parser/src/values/file_flags_values.dart';
import 'package:fit_parser/src/values/file_values.dart';
import 'package:fit_parser/src/values/fit_base_type_values.dart';
import 'package:fit_parser/src/values/fit_base_unit_values.dart';
import 'package:fit_parser/src/values/fitness_equipment_state_values.dart';
import 'package:fit_parser/src/values/flye_exercise_name_values.dart';
import 'package:fit_parser/src/values/garmin_product_values.dart';
import 'package:fit_parser/src/values/gender_values.dart';
import 'package:fit_parser/src/values/goal_recurrence_values.dart';
import 'package:fit_parser/src/values/goal_source_values.dart';
import 'package:fit_parser/src/values/goal_values.dart';
import 'package:fit_parser/src/values/hip_raise_exercise_name_values.dart';
import 'package:fit_parser/src/values/hip_stability_exercise_name_values.dart';
import 'package:fit_parser/src/values/hip_swing_exercise_name_values.dart';
import 'package:fit_parser/src/values/hr_type_values.dart';
import 'package:fit_parser/src/values/hr_zone_calc_values.dart';
import 'package:fit_parser/src/values/hyperextension_exercise_name_values.dart';
import 'package:fit_parser/src/values/intensity_values.dart';
import 'package:fit_parser/src/values/language_bits_0_values.dart';
import 'package:fit_parser/src/values/language_bits_1_values.dart';
import 'package:fit_parser/src/values/language_bits_2_values.dart';
import 'package:fit_parser/src/values/language_bits_3_values.dart';
import 'package:fit_parser/src/values/language_bits_4_values.dart';
import 'package:fit_parser/src/values/language_values.dart';
import 'package:fit_parser/src/values/lap_trigger_values.dart';
import 'package:fit_parser/src/values/lateral_raise_exercise_name_values.dart';
import 'package:fit_parser/src/values/left_right_balance_100_values.dart';
import 'package:fit_parser/src/values/left_right_balance_values.dart';
import 'package:fit_parser/src/values/leg_curl_exercise_name_values.dart';
import 'package:fit_parser/src/values/leg_raise_exercise_name_values.dart';
import 'package:fit_parser/src/values/length_type_values.dart';
import 'package:fit_parser/src/values/lunge_exercise_name_values.dart';
import 'package:fit_parser/src/values/manufacturer_values.dart';
import 'package:fit_parser/src/values/mesg_count_values.dart';
import 'package:fit_parser/src/values/mesg_num_values.dart';
import 'package:fit_parser/src/values/message_index_values.dart';
import 'package:fit_parser/src/values/olympic_lift_exercise_name_values.dart';
import 'package:fit_parser/src/values/plank_exercise_name_values.dart';
import 'package:fit_parser/src/values/plyo_exercise_name_values.dart';
import 'package:fit_parser/src/values/power_phase_type_values.dart';
import 'package:fit_parser/src/values/pull_up_exercise_name_values.dart';
import 'package:fit_parser/src/values/push_up_exercise_name_values.dart';
import 'package:fit_parser/src/values/pwr_zone_calc_values.dart';
import 'package:fit_parser/src/values/rider_position_type_values.dart';
import 'package:fit_parser/src/values/row_exercise_name_values.dart';
import 'package:fit_parser/src/values/run_exercise_name_values.dart';
import 'package:fit_parser/src/values/schedule_values.dart';
import 'package:fit_parser/src/values/segment_delete_status_values.dart';
import 'package:fit_parser/src/values/segment_lap_status_values.dart';
import 'package:fit_parser/src/values/segment_leaderboard_type_values.dart';
import 'package:fit_parser/src/values/segment_selection_type_values.dart';
import 'package:fit_parser/src/values/sensor_type_values.dart';
import 'package:fit_parser/src/values/session_trigger_values.dart';
import 'package:fit_parser/src/values/set_type_values.dart';
import 'package:fit_parser/src/values/shoulder_press_exercise_name_values.dart';
import 'package:fit_parser/src/values/shoulder_stability_exercise_name_values.dart';
import 'package:fit_parser/src/values/shrug_exercise_name_values.dart';
import 'package:fit_parser/src/values/side_values.dart';
import 'package:fit_parser/src/values/sit_up_exercise_name_values.dart';
import 'package:fit_parser/src/values/source_type_values.dart';
import 'package:fit_parser/src/values/sport_bits_0_values.dart';
import 'package:fit_parser/src/values/sport_bits_1_values.dart';
import 'package:fit_parser/src/values/sport_bits_2_values.dart';
import 'package:fit_parser/src/values/sport_bits_3_values.dart';
import 'package:fit_parser/src/values/sport_bits_4_values.dart';
import 'package:fit_parser/src/values/sport_bits_5_values.dart';
import 'package:fit_parser/src/values/sport_event_values.dart';
import 'package:fit_parser/src/values/sport_values.dart';
import 'package:fit_parser/src/values/squat_exercise_name_values.dart';
import 'package:fit_parser/src/values/stroke_type_values.dart';
import 'package:fit_parser/src/values/sub_sport_values.dart';
import 'package:fit_parser/src/values/supported_exd_screen_layouts_values.dart';
import 'package:fit_parser/src/values/swim_stroke_values.dart';
import 'package:fit_parser/src/values/switch_values.dart';
import 'package:fit_parser/src/values/time_mode_values.dart';
import 'package:fit_parser/src/values/time_zone_values.dart';
import 'package:fit_parser/src/values/timer_trigger_values.dart';
import 'package:fit_parser/src/values/tone_values.dart';
import 'package:fit_parser/src/values/total_body_exercise_name_values.dart';
import 'package:fit_parser/src/values/triceps_extension_exercise_name_values.dart';
import 'package:fit_parser/src/values/turn_type_values.dart';
import 'package:fit_parser/src/values/user_local_id_values.dart';
import 'package:fit_parser/src/values/warm_up_exercise_name_values.dart';
import 'package:fit_parser/src/values/watchface_mode_values.dart';
import 'package:fit_parser/src/values/water_type_values.dart';
import 'package:fit_parser/src/values/weather_report_values.dart';
import 'package:fit_parser/src/values/weather_severe_type_values.dart';
import 'package:fit_parser/src/values/weather_severity_values.dart';
import 'package:fit_parser/src/values/weather_status_values.dart';
import 'package:fit_parser/src/values/wkt_step_duration_values.dart';
import 'package:fit_parser/src/values/wkt_step_target_values.dart';
import 'package:fit_parser/src/values/workout_capabilities_values.dart';
import 'package:fit_parser/src/values/workout_equipment_values.dart';

class FitType {
  static Map type = {
// A
    'activity': activityValues,
    'activity_class': activityClassValues,
    'activity_level': activityLevelValues,
    'activity_subtype': activitySubtypeValues,
    'activity_type': activityTypeValues,
    'analog_watchface_layout': analogWatchfaceLayoutValues,
    'ant_network': antNetworkValues,
    'antplus_device_type': antplusDeviceTypeValues,
    'attitude_stage': attitudeStageValues,
    'attitude_validity': attitudeValidityValues,
    'auto_activity_detect': autoActivityDetectValues,
    'autolap_trigger': autolapTriggerValues,
    'autoscroll': autoscrollValues,
    'auto_sync_frequency': autoSyncFrequencyValues,
// B
    'backlight_mode': backlightModeValues,
    'backlight_timeout': {
      0: 'infinite',
    },
    'battery_status': batteryStatusValues,
    'bench_press_exercise_name': benchPressExerciseNameValues,
    'bike_light_beam_angle_mode': bikeLightBeamAngleModeValues,
    'bike_light_network_config_type': bikeLightNetworkConfigTypeValues,
    'body_location': bodyLocationValues,
    'bp_status': bpStatusValues,
// C
    'calf_raise_exercise_name': calfRaiseExerciseNameValues,
    'camera_event_type': cameraEventTypeValues,
    'camera_orientation_type': cameraOrientationTypeValues,
    'cardio_exercise_name': cardioExerciseNameValues,
    'carry_exercise_name': carryExerciseNameValues,
    'checksum': checksumValues,
    'chop_exercise_name': chopExerciseNameValues,
    'comm_timeout_type': commTimeoutTypeValues,
    'connectivity_capabilities': connectivityCapabilitiesValues,
    'core_exercise_name': coreExerciseNameValues,
    'course_capabilities': courseCapabilitiesValues,
    'course_point': coursePointValues,
    'crunch_exercise_name': crunchExerciseNameValues,
    'curl_exercise_name': curlExerciseNameValues,
// D
    'date_mode': dateModeValues,
    'date_time': {
      0x10000000: 'min',
    },
    'day_of_week': dayOfWeekValues,
    'deadlift_exercise_name': deadliftExerciseNameValues,
    'device_index': {
      0: 'creator',
    },
    'digital_watchface_layout': digitalWatchfaceLayoutValues,
    'display_heart': displayHeartValues,
    'display_measure': displayMeasureValues,
    'display_orientation': displayOrientationValues,
    'display_position': displayPositionValues,
    'display_power': displayPowerValues,
    'dive_alarm_type': diveAlarmTypeValues,
    'dive_backlight_mode': diveBacklightModeValues,
    'dive_gas_status': diveGasStatusValues,
// E
    'event': eventValues,
    'event_type': eventTypeValues,
    'exd_data_units': exdDataUnitsValues,
    'exd_descriptors': exdDescriptorsValues,
    'exd_display_type': exdDisplayTypeValues,
    'exd_layout': exdLayoutValues,
    'exd_qualifiers': exdQualifiersValues,
    'exercise_category': exerciseCategoryValues,
// F
    'favero_product': faveroProductValues,
    'file': fileValues,
    'file_flags': fileFlagsValues,
    'fit_base_type': fitBaseTypeValues,
    'fit_base_unit': fitBaseUnitValues,
    'fitness_equipment_state': fitnessEquipmentStateValues,
    'flye_exercise_name': flyeExerciseNameValues,
// G
    'garmin_product': garminProductValues,
    'gender': genderValues,
    'goal': goalValues,
    'goal_recurrence': goalRecurrenceValues,
    'goal_source': goalSourceValues,
// H
    'hip_raise_exercise_name': hipRaiseExerciseNameValues,
    'hip_stability_exercise_name': hipStabilityExerciseNameValues,
    'hip_swing_exercise_name': hipSwingExerciseNameValues,
    'hr_type': hrTypeValues,
    'hr_zone_calc': hrZoneCalcValues,
    'hyperextension_exercise_name': hyperextensionExerciseNameValues,
// I
    'intensity': intensityValues,
// L
    'language': languageValues,
    'language_bits_0': languageBits_0Values,
    'language_bits_1': languageBits_1Values,
    'language_bits_2': languageBits_2Values,
    'language_bits_3': languageBits_3Values,
    'language_bits_4': languageBits_4Values,
    'lap_trigger': lapTriggerValues,
    'lateral_raise_exercise_name': lateralRaiseExerciseNameValues,
    'left_right_balance': leftRightBalanceValues,
    'left_right_balance_100': leftRightBalance_100Values,
    'leg_curl_exercise_name': legCurlExerciseNameValues,
    'leg_raise_exercise_name': legRaiseExerciseNameValues,
    'length_type': lengthTypeValues,
    'local_date_time': {
      0x10000000: 'min',
    },
    'lunge_exercise_name': lungeExerciseNameValues,
// M
    'manufacturer': manufacturerValues,
    'mesg_count': mesgCountValues,
    'mesg_num': mesgNumValues,
    'message_index': messageIndexValues,
// O
    'olympic_lift_exercise_name': olympicLiftExerciseNameValues,
// P
    'plank_exercise_name': plankExerciseNameValues,
    'plyo_exercise_name': plyoExerciseNameValues,
    'power_phase_type': powerPhaseTypeValues,
    'pull_up_exercise_name': pullUpExerciseNameValues,
    'push_up_exercise_name': pushUpExerciseNameValues,
    'pwr_zone_calc': pwrZoneCalcValues,
// R
    'rider_position_type': riderPositionTypeValues,
    'row_exercise_name': rowExerciseNameValues,
    'run_exercise_name': runExerciseNameValues,
// S
    'schedule': scheduleValues,
    'segment_delete_status': segmentDeleteStatusValues,
    'segment_lap_status': segmentLapStatusValues,
    'segment_leaderboard_type': segmentLeaderboardTypeValues,
    'segment_selection_type': segmentSelectionTypeValues,
    'sensor_type': sensorTypeValues,
    'session_trigger': sessionTriggerValues,
    'set_type': setTypeValues,
    'shoulder_press_exercise_name': shoulderPressExerciseNameValues,
    'shoulder_stability_exercise_name': shoulderStabilityExerciseNameValues,
    'shrug_exercise_name': shrugExerciseNameValues,
    'side': sideValues,
    'sit_up_exercise_name': sitUpExerciseNameValues,
    'source_type': sourceTypeValues,
    'sport': sportValues,
    'sport_bits_0': sportBits0Values,
    'sport_bits_1': sportBits1Values,
    'sport_bits_2': sportBits2Values,
    'sport_bits_3': sportBits3Values,
    'sport_bits_4': sportBits4Values,
    'sport_bits_5': sportBits5Values,
    'sport_bits_6': {
      0x01: 'floor_climbing',
    },
    'sport_event': sportEventValues,
    'squat_exercise_name': squatExerciseNameValues,
    'stroke_type': strokeTypeValues,
    'sub_sport': subSportValues,
    'supported_exd_screen_layouts': supportedExdScreenLayoutsValues,
    'swim_stroke': swimStrokeValues,
    'switch': switchValues,
// T
    'time_mode': timeModeValues,
    'time_zone': timeZoneValues,
    'timer_trigger': timerTriggerValues,
    'tissue_model_type': {
      0: 'zhl_16c',
    },
    'tone': toneValues,
    'total_body_exercise_name': totalBodyExerciseNameValues,
    'triceps_extension_exercise_name': tricepsExtensionExerciseNameValues,
    'turn_type': turnTypeValues,
// U
    'user_local_id': userLocalIdValues,
// W
    'warm_up_exercise_name': warmUpExerciseNameValues,
    'watchface_mode': watchfaceModeValues,
    'water_type': waterTypeValues,
    'weather_report': weatherReportValues,
    'weather_severe_type': weatherSevereTypeValues,
    'weather_severity': weatherSeverityValues,
    'weather_status': weatherStatusValues,
    'weight': {
      0xFFFE: 'calculating',
    },
    'wkt_step_duration': wktStepDurationValues,
    'wkt_step_target': wktStepTargetValues,
    'workout_capabilities': workoutCapabilitiesValues,
    'workout_equipment': workoutEquipmentValues,
    'workout_hr': {
      100: 'bpm_offset',
    },
    'workout_power': {
      1000: 'watts_offset',
    },
  };
}
