Map baseTypes = {
  0: {
    'type_name': 'enum',
    'endian_ability': 0,
    'base_type_field': 0x00,
    'invalid_value': 0xFF,
    'size': 1,
  },
  1: {
    'type_name': 'sint8',
    'endian_ability': 0,
    'base_type_field': 0x01,
    'invalid_value': 0x7F,
    'size': 1,
  },
  2: {
    'type_name': 'uint8',
    'endian_ability': 0,
    'base_type_field': 0x02,
    'invalid_value': 0xFF,
    'size': 1,
  },
  3: {
    'type_name': 'sint16',
    'endian_ability': 1,
    'base_type_field': 0x83,
    'invalid_value': 0x7FFF,
    'size': 2,
  },
  4: {
    'type_name': 'uint16',
    'endian_ability': 1,
    'base_type_field': 0x84,
    'invalid_value': 0xFFFF,
    'size': 2,
  },
  5: {
    'type_name': 'sint32',
    'endian_ability': 1,
    'base_type_field': 0x85,
    'invalid_value': 0x7FFFFFFF,
    'size': 4,
  },
  6: {
    'type_name': 'uint32',
    'endian_ability': 1,
    'base_type_field': 0x86,
    'invalid_value': 0xFFFFFFFF,
    'size': 4,
  },
  7: {
    'type_name': 'string',
    'endian_ability': 0,
    'base_type_field': 0x07,
    'invalid_value': 0x00,
    'size': 1,
  },
  8: {
    'type_name': 'float32',
    'endian_ability': 1,
    'base_type_field': 0x88,
    'invalid_value': 0xFFFFFFFF,
    'size': 4,
  },
  9: {
    'type_name': 'float64',
    'endian_ability': 1,
    'base_type_field': 0x89,
    'invalid_value': 0xFFFFFFFFFFFFFFFF,
    'size': 8,
  },
  10: {
    'type_name': 'uint8z',
    'endian_ability': 0,
    'base_type_field': 0x0A,
    'invalid_value': 0x00,
    'size': 1,
  },
  11: {
    'type_name': 'uint16z',
    'endian_ability': 1,
    'base_type_field': 0x8B,
    'invalid_value': 0x0000,
    'size': 2,
  },
  12: {
    'type_name': 'uint32z',
    'endian_ability': 1,
    'base_type_field': 0x8C,
    'invalid_value': 0x00000000,
    'size': 4,
  },
  13: {
    'type_name': 'byte',
    'endian_ability': 0,
    'base_type_field': 0x0D,
    'invalid_value': 0xFF,
    'size': 1,
  },
  14: {
    'type_name': 'sint64',
    'endian_ability': 1,
    'base_type_field': 0x8E,
    'invalid_value': 0x7FFFFFFFFFFFFFFF,
    'size': 8,
  },
  15: {
    'type_name': 'uint64',
    'endian_ability': 1,
    'base_type_field': 0x8F,
    'invalid_value': 0xFFFFFFFFFFFFFFFF,
    'size': 8,
  },
  16: {
    'type_name': 'uint64z',
    'endian_ability': 1,
    'base_type_field': 0x90,
    'invalid_value': 0x0000000000000000,
    'size': 8,
  },
};
