Map activity_subtype_values = {
  0: 'generic',
  1: 'treadmill',
  2: 'street',
  3: 'trail',
  4: 'track',
  5: 'spin',
  6: 'indoor_cycling',
  7: 'road',
  8: 'mountain',
  9: 'downhill',
  10: 'recumbent',
  11: 'cyclocross',
  12: 'hand_cycling',
  13: 'track_cycling',
  14: 'indoor_rowing',
  15: 'elliptical',
  16: 'stair_climbing',
  17: 'lap_swimming',
  18: 'open_water',
  254: 'all',
};
