Map antplusDeviceTypeValues = {
  1: 'antfs',
  11: 'bike_power',
  12: 'environment_sensor_legacy',
  15: 'multi_sport_speed_distance',
  16: 'control',
  17: 'fitness_equipment',
  18: 'blood_pressure',
  19: 'geocache_node',
  20: 'light_electric_vehicle',
  25: 'env_sensor',
  26: 'racquet',
  27: 'control_hub',
  31: 'muscle_oxygen',
  35: 'bike_light_main',
  36: 'bike_light_shared',
  38: 'exd',
  40: 'bike_radar',
  46: 'bike_aero',
  119: 'weight_scale',
  120: 'heart_rate',
  121: 'bike_speed_cadence',
  122: 'bike_cadence',
  123: 'bike_speed',
  124: 'stride_speed_distance',
};
