Map calf_raise_exercise_name_values = {
  0: '3_way_calf_raise',
  1: '3_way_weighted_calf_raise',
  2: '3_way_single_leg_calf_raise',
  3: '3_way_weighted_single_leg_calf_raise',
  4: 'donkey_calf_raise',
  5: 'weighted_donkey_calf_raise',
  6: 'seated_calf_raise',
  7: 'weighted_seated_calf_raise',
  8: 'seated_dumbbell_toe_raise',
  9: 'single_leg_bent_knee_calf_raise',
  10: 'weighted_single_leg_bent_knee_calf_raise',
  11: 'single_leg_decline_push_up',
  12: 'single_leg_donkey_calf_raise',
  13: 'weighted_single_leg_donkey_calf_raise',
  14: 'single_leg_hip_raise_with_knee_hold',
  15: 'single_leg_standing_calf_raise',
  16: 'single_leg_standing_dumbbell_calf_raise',
  17: 'standing_barbell_calf_raise',
  18: 'standing_calf_raise',
  19: 'weighted_standing_calf_raise',
  20: 'standing_dumbbell_calf_raise',
};