Map cardioExerciseNameValues = {
  0: 'bob_and_weave_circle',
  1: 'weighted_bob_and_weave_circle',
  2: 'cardio_core_crawl',
  3: 'weighted_cardio_core_crawl',
  4: 'double_under',
  5: 'weighted_double_under',
  6: 'jump_rope',
  7: 'weighted_jump_rope',
  8: 'jump_rope_crossover',
  9: 'weighted_jump_rope_crossover',
  10: 'jump_rope_jog',
  11: 'weighted_jump_rope_jog',
  12: 'jumping_jacks',
  13: 'weighted_jumping_jacks',
  14: 'ski_moguls',
  15: 'weighted_ski_moguls',
  16: 'split_jacks',
  17: 'weighted_split_jacks',
  18: 'squat_jacks',
  19: 'weighted_squat_jacks',
  20: 'triple_under',
  21: 'weighted_triple_under',
};
