Map chop_exercise_name_values = {
  0: 'cable_pull_through',
  1: 'cable_rotational_lift',
  2: 'cable_woodchop',
  3: 'cross_chop_to_knee',
  4: 'weighted_cross_chop_to_knee',
  5: 'dumbbell_chop',
  6: 'half_kneeling_rotation',
  7: 'weighted_half_kneeling_rotation',
  8: 'half_kneeling_rotational_chop',
  9: 'half_kneeling_rotational_reverse_chop',
  10: 'half_kneeling_stability_chop',
  11: 'half_kneeling_stability_reverse_chop',
  12: 'kneeling_rotational_chop',
  13: 'kneeling_rotational_reverse_chop',
  14: 'kneeling_stability_chop',
  15: 'kneeling_woodchopper',
  16: 'medicine_ball_wood_chops',
  17: 'power_squat_chops',
  18: 'weighted_power_squat_chops',
  19: 'standing_rotational_chop',
  20: 'standing_split_rotational_chop',
  21: 'standing_split_rotational_reverse_chop',
  22: 'standing_stability_reverse_chop',
};
