Map coursePointValues = {
  0: 'generic',
  1: 'summit',
  2: 'valley',
  3: 'water',
  4: 'food',
  5: 'danger',
  6: 'left',
  7: 'right',
  8: 'straight',
  9: 'first_aid',
  10: 'fourth_category',
  11: 'third_category',
  12: 'second_category',
  13: 'first_category',
  14: 'hors_category',
  15: 'sprint',
  16: 'left_fork',
  17: 'right_fork',
  18: 'middle_fork',
  19: 'slight_left',
  20: 'sharp_left',
  21: 'slight_right',
  22: 'sharp_right',
  23: 'u_turn',
  24: 'segment_start',
  25: 'segment_end',
};
