Map deadlift_exercise_name_values = {
  0: 'barbell_deadlift',
  1: 'barbell_straight_leg_deadlift',
  2: 'dumbbell_deadlift',
  3: 'dumbbell_single_leg_deadlift_to_row',
  4: 'dumbbell_straight_leg_deadlift',
  5: 'kettlebell_floor_to_shelf',
  6: 'one_arm_one_leg_deadlift',
  7: 'rack_pull',
  8: 'rotational_dumbbell_straight_leg_deadlift',
  9: 'single_arm_deadlift',
  10: 'single_leg_barbell_deadlift',
  11: 'single_leg_barbell_straight_leg_deadlift',
  12: 'single_leg_deadlift_with_barbell',
  13: 'single_leg_rdl_circuit',
  14: 'single_leg_romanian_deadlift_with_dumbbell',
  15: 'sumo_deadlift',
  16: 'sumo_deadlift_high_pull',
  17: 'trap_bar_deadlift',
  18: 'wide_grip_barbell_deadlift',
};