Map fileValues = {
  1: 'device',
  2: 'settings',
  3: 'sport',
  4: 'activity',
  5: 'workout',
  6: 'course',
  7: 'schedules',
  9: 'weight',
  10: 'totals',
  11: 'goals',
  14: 'blood_pressure',
  15: 'monitoring_a',
  20: 'activity_summary',
  28: 'monitoring_daily',
  32: 'monitoring_b',
  34: 'segment',
  35: 'segment_list',
  40: 'exd_configuration',
  0xF7: 'mfg_range_min',
  0xFE: 'mfg_range_max',
};
