Map legRaiseExerciseNameValues = {
  0: 'hanging_knee_raise',
  1: 'hanging_leg_raise',
  2: 'weighted_hanging_leg_raise',
  3: 'hanging_single_leg_raise',
  4: 'weighted_hanging_single_leg_raise',
  5: 'kettlebell_leg_raises',
  6: 'leg_lowering_drill',
  7: 'weighted_leg_lowering_drill',
  8: 'lying_straight_leg_raise',
  9: 'weighted_lying_straight_leg_raise',
  10: 'medicine_ball_leg_drops',
  11: 'quadruped_leg_raise',
  12: 'weighted_quadruped_leg_raise',
  13: 'reverse_leg_raise',
  14: 'weighted_reverse_leg_raise',
  15: 'reverse_leg_raise_on_swiss_ball',
  16: 'weighted_reverse_leg_raise_on_swiss_ball',
  17: 'single_leg_lowering_drill',
  18: 'weighted_single_leg_lowering_drill',
  19: 'weighted_hanging_knee_raise',
  20: 'lateral_stepover',
  21: 'weighted_lateral_stepover',
};
