Map olympic_lift_exercise_name_values = {
  0: 'barbell_hang_power_clean',
  1: 'barbell_hang_squat_clean',
  2: 'barbell_power_clean',
  3: 'barbell_power_snatch',
  4: 'barbell_squat_clean',
  5: 'clean_and_jerk',
  6: 'barbell_hang_power_snatch',
  7: 'barbell_hang_pull',
  8: 'barbell_high_pull',
  9: 'barbell_snatch',
  10: 'barbell_split_jerk',
  11: 'clean',
  12: 'dumbbell_clean',
  13: 'dumbbell_hang_pull',
  14: 'one_hand_dumbbell_split_snatch',
  15: 'push_jerk',
  16: 'single_arm_dumbbell_snatch',
  17: 'single_arm_hang_snatch',
  18: 'single_arm_kettlebell_snatch',
  19: 'split_jerk',
  20: 'squat_clean_and_jerk',
};
