Map shoulder_press_exercise_name_values = {
  0: 'alternating_dumbbell_shoulder_press',
  1: 'arnold_press',
  2: 'barbell_front_squat_to_push_press',
  3: 'barbell_push_press',
  4: 'barbell_shoulder_press',
  5: 'dead_curl_press',
  6: 'dumbbell_alternating_shoulder_press_and_twist',
  7: 'dumbbell_hammer_curl_to_lunge_to_press',
  8: 'dumbbell_push_press',
  9: 'floor_inverted_shoulder_press',
  10: 'weighted_floor_inverted_shoulder_press',
  11: 'inverted_shoulder_press',
  12: 'weighted_inverted_shoulder_press',
  13: 'one_arm_push_press',
  14: 'overhead_barbell_press',
  15: 'overhead_dumbbell_press',
  16: 'seated_barbell_shoulder_press',
  17: 'seated_dumbbell_shoulder_press',
  18: 'single_arm_dumbbell_shoulder_press',
  19: 'single_arm_step_up_and_press',
  20: 'smith_machine_overhead_press',
  21: 'split_stance_hammer_curl_to_press',
  22: 'swiss_ball_dumbbell_shoulder_press',
  23: 'weight_plate_front_raise',
};
