Map shrug_exercise_name_values = {
  0: 'barbell_jump_shrug',
  1: 'barbell_shrug',
  2: 'barbell_upright_row',
  3: 'behind_the_back_smith_machine_shrug',
  4: 'dumbbell_jump_shrug',
  5: 'dumbbell_shrug',
  6: 'dumbbell_upright_row',
  7: 'incline_dumbbell_shrug',
  8: 'overhead_barbell_shrug',
  9: 'overhead_dumbbell_shrug',
  10: 'scaption_and_shrug',
  11: 'scapular_retraction',
  12: 'serratus_chair_shrug',
  13: 'weighted_serratus_chair_shrug',
  14: 'serratus_shrug',
  15: 'weighted_serratus_shrug',
  16: 'wide_grip_jump_shrug',
};