Map weather_status_values = {
  0: 'clear',
  1: 'partly_cloudy',
  2: 'mostly_cloudy',
  3: 'rain',
  4: 'snow',
  5: 'windy',
  6: 'thunderstorms',
  7: 'wintry_mix',
  8: 'fog',
  11: 'hazy',
  12: 'hail',
  13: 'scattered_showers',
  14: 'scattered_thunderstorms',
  15: 'unknown_precipitation',
  16: 'light_rain',
  17: 'heavy_rain',
  18: 'light_snow',
  19: 'heavy_snow',
  20: 'light_rain_snow',
  21: 'heavy_rain_snow',
  22: 'cloudy',
};